import type { Metadata } from "next";
import { Fraunces, DM_Sans } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import Providers from "./providers";
import BackToTop from "@/components/BackToTopButton";

const fraunces = Fraunces({ 
  subsets: ["latin"], 
  variable: "--font-heading" 
});

const dmSans = DM_Sans ({ 
  subsets: ["latin"], 
  variable: "--font-body" 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${fraunces.variable} ${dmSans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Providers>
          <Navbar />
          <main>{children}</main>
        </Providers>
        <Footer />
        <BackToTop />
      </body>
    </html>
  );
}
